---

- project:
    name: graffiti
    check:
      jobs:
        - tox-pep8:
            nodeset:
              nodes:
                - name: fedora-rawhide
                  label: cloud-fedora-rawhide
        - tox-py39:
            nodeset:
              nodes:
                - name: centos-9-stream
                  label: cloud-centos-9-stream
            vars:
                tox_install_bindep: false
    gate:
      jobs:
        - tox-pep8:
            nodeset:
              nodes:
                - name: fedora-rawhide
                  label: cloud-fedora-rawhide
        - tox-py39:
            nodeset:
              nodes:
                - name: centos-9-stream
                  label: cloud-centos-9-stream
            vars:
                tox_install_bindep: false
